version: "3"
services:
  api-server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    networks:
      - kido-verse-app
    env_file:
      - ./.env
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - kido-verse-app
    volumes:
      - mongo-data:/data/db
networks:
  kido-verse-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local